/**
 * Geographic codes for worker profile forms.
 *
 * State codes use FIPS 5-2 numeric codes (u16).
 * Country codes use ISO 3166-1 numeric codes (u16).
 */

export const US_STATE_CODES: { code: number; label: string }[] = [
  { code: 1, label: "Alabama" },
  { code: 2, label: "Alaska" },
  { code: 4, label: "Arizona" },
  { code: 5, label: "Arkansas" },
  { code: 6, label: "California" },
  { code: 8, label: "Colorado" },
  { code: 9, label: "Connecticut" },
  { code: 10, label: "Delaware" },
  { code: 11, label: "District of Columbia" },
  { code: 12, label: "Florida" },
  { code: 13, label: "Georgia" },
  { code: 15, label: "Hawaii" },
  { code: 16, label: "Idaho" },
  { code: 17, label: "Illinois" },
  { code: 18, label: "Indiana" },
  { code: 19, label: "Iowa" },
  { code: 20, label: "Kansas" },
  { code: 21, label: "Kentucky" },
  { code: 22, label: "Louisiana" },
  { code: 23, label: "Maine" },
  { code: 24, label: "Maryland" },
  { code: 25, label: "Massachusetts" },
  { code: 26, label: "Michigan" },
  { code: 27, label: "Minnesota" },
  { code: 28, label: "Mississippi" },
  { code: 29, label: "Missouri" },
  { code: 30, label: "Montana" },
  { code: 31, label: "Nebraska" },
  { code: 32, label: "Nevada" },
  { code: 33, label: "New Hampshire" },
  { code: 34, label: "New Jersey" },
  { code: 35, label: "New Mexico" },
  { code: 36, label: "New York" },
  { code: 37, label: "North Carolina" },
  { code: 38, label: "North Dakota" },
  { code: 39, label: "Ohio" },
  { code: 40, label: "Oklahoma" },
  { code: 41, label: "Oregon" },
  { code: 42, label: "Pennsylvania" },
  { code: 44, label: "Rhode Island" },
  { code: 45, label: "South Carolina" },
  { code: 46, label: "South Dakota" },
  { code: 47, label: "Tennessee" },
  { code: 48, label: "Texas" },
  { code: 49, label: "Utah" },
  { code: 50, label: "Vermont" },
  { code: 51, label: "Virginia" },
  { code: 53, label: "Washington" },
  { code: 54, label: "West Virginia" },
  { code: 55, label: "Wisconsin" },
  { code: 56, label: "Wyoming" },
  // Territories
  { code: 60, label: "American Samoa" },
  { code: 66, label: "Guam" },
  { code: 69, label: "Northern Mariana Islands" },
  { code: 72, label: "Puerto Rico" },
  { code: 78, label: "U.S. Virgin Islands" },
];

export const COUNTRY_CODES: { code: number; label: string }[] = [
  { code: 840, label: "United States" },
  { code: 124, label: "Canada" },
  { code: 484, label: "Mexico" },
  { code: 32, label: "Argentina" },
  { code: 76, label: "Brazil" },
  { code: 152, label: "Chile" },
  { code: 170, label: "Colombia" },
  { code: 188, label: "Costa Rica" },
  { code: 214, label: "Dominican Republic" },
  { code: 218, label: "Ecuador" },
  { code: 222, label: "El Salvador" },
  { code: 320, label: "Guatemala" },
  { code: 332, label: "Haiti" },
  { code: 340, label: "Honduras" },
  { code: 388, label: "Jamaica" },
  { code: 558, label: "Nicaragua" },
  { code: 591, label: "Panama" },
  { code: 600, label: "Paraguay" },
  { code: 604, label: "Peru" },
  { code: 780, label: "Trinidad and Tobago" },
  { code: 858, label: "Uruguay" },
  { code: 862, label: "Venezuela" },
  // Additional
  { code: 826, label: "United Kingdom" },
  { code: 276, label: "Germany" },
  { code: 250, label: "France" },
  { code: 356, label: "India" },
  { code: 156, label: "China" },
  { code: 392, label: "Japan" },
  { code: 410, label: "South Korea" },
  { code: 608, label: "Philippines" },
  { code: 704, label: "Vietnam" },
];
